### ISSUE TITLE
Version 2 of the CMS

### ISSUE THREAD

**Issue by danielsamuels** [onespacemedia/cms#18]
Over the past few years the CMS has grown enormously in size, gaining new features and benefits seemingly every month.  For Version 2 I would like to propose a streamlining drive where any unnecessary code is stripped out, any unused features are removed and any third-party services which can be integrated cleanly can be done so.

In general, I would like to reduce the number of dependancies the CMS has while still providing all of the functionality we and our clients need to produce world-class web applications.

With this in mind, here are the key points that I propose:
- [ ] Break the regionalisation system out into a modular framework which can integrate with any model, including those contained with the CMS and it's apps.
- [ ] Improve the page management system, allow users to drag-and-drop pages around to change the ordering.
- [x] Extend front-end permissions, allow admins to restrict pages to certain user groups such as logged-in users, or any given criteria.
- [ ] Provide the ability to maintain multiple versions of the same page, both in a regional context but also a 'draft state' context.
- [ ] Restyle the admin system to look like the front-end site, bring in the brand colours, logos and improve the overall look-and-feel of the back-end.
- [ ] Provide a meaningful changelog.
- [ ] Maintain documentation.
- [x] Maintain 100% code coverage.
- [x] Make applications easier to modify, such as adding new fields to existing models or adding new functionality to views.
- [x] Improve the SEO tools that are available, bring in new web features such as OpenGraph and add email markup tools.
- [x] Vastly improve the Sections feature, potentially bringing it into the core CMS and making it extensible.
- [x] Reduce the number of external dependancies and bring features into the CMS if possible.
- [x] Provide a greater level of control over moderation in the admin, adding the concept of sub-editors who are allowed to create objects such as pages but have them held in a queue until a editor approves them.
- [ ] Improve the dashboard view, provide clients with a greater insight into what's happening with their website.
- [ ] Evaluate existing projects and determine which sections of CMS code are never used, remove them.
- [x] Improve the version labelling scheme.
- [ ] Move completely to Python 3.
- [x] Move to a pull request based system whereby tests and coverage information is generated before pushing into master.
- [ ] Automate releases.

**Comment by danielsamuels** [comment]
# Project dependancies

This a list of all of the dependancies the CMS currently has and my evaluation of whether it is required.

### django

Required.

### psycopg2

Required.

### django-suit

Not required. When we redesign the admin this can be removed.

### Pillow

Required for image manipulation.

### django-reversion

Required to allow users to rollback their changes. Needs to be used more in custom models.

### django-historylinks

A useful tool for maintaining historical links. Could potentially be brought into the core of the CMS.

### django-watson

Provides a great search backend, we use it well.

### django-extensions

Only used during development, but a useful thing to have.

### Werkzeug

Also only used during development, but useful to have.

### raven

Provides our Sentry integration. This may be phased out in favour of Opbeat.

### django-compressor

Used to minify our CSS and JS. This could be done with Gulp.

### sorl-thumbnail

Used for thumbnailing, useful to have.

### bcrypt

Used for improving password security, required.

### onespacemedia-server-management

Used for deploying and managing servers. Could potentially be brought into the project, but works well as an external dependancy.  It's dependancies are reliant on Python 2 is limiting for the CMS as a whole.

### requests

Used to bring in images from a remote source for the Adobe SDK. Could potentially be replaced with urllib2.

### python-social-auth

Used to allow Onespacemedia staff to log in automatically. Has it's own problems (particulary around losing names and the amount of effort required for setup). Could potentially be brought into the project.

### django-cachalot

Used for simple caching of queries, makes sites faster with no code required.

### python-memcached

Used in conjunction with Cachalot primarily, but other services can make use of it too.

### geoip

Used to Geolocate users for the regionalisation work. Could be removed upon a rework of the languages system if it were to be based on browser headers or similar.

**Comment by DanGamble89** [comment]
#### Dependencies
| Keep | Lose | Core | Local.txt
| ------- | ------ | ---------| ---- |
| Django | django-suit | django-historylinks | django-extensions
| psycopg2 | django-compressor | requests (urllib2) | Werkzeug |
| Pillow | | python-social-auth |
| django-reversion
| django-watson
| Raven/Opbeat
| sort-thumbnail
| bcrypt
| django-cachalot
| python-memcached
| geoip

#### Undecided:

##### onespacemedia-server-management
Could this be done in something like Go or Node, maybe even in the Gulp tool. I'm not sure how extensive it can be with the venv stuff we use as i'm personally not that clued up on Fabric / Ansible and not sure if they offer something truly unique because they are Python based

#### Lose:

##### django-suit
We would be doing our own frontend thing on this so going for an all in custom admin.

##### django-compressor
I think all of this could be done in Gulp, maybe create a build task that does all this that gets ran during the deployment / update tasks we run. Minification + Concatenation is all pretty simple in it. Does django-compressor offer anything else besides them?

#### Core:

##### django-historylinks
For the reason you mentioned would be nice to just shave off another dependancy

##### python-social-auth
Since we have had a few problems with this and it seems to no longer be maintained probably makes sense to bring it into the core

##### requests (urllib2)
Since we are going to P3 it makes sense to use the inbuilt urllib2 vs an external for this as well, imo

#### Local.txt:
Just seperate the requirements.txt into a directory like the settings and have environment based requirement files to help slim down on where we use the dependancies

**Comment by danielsamuels** [comment]
Add page concept: http://codepen.io/danielsamuels/full/GJjOPW/
Manage page concept: http://codepen.io/danielsamuels/full/GJjOem/

**Comment by danielsamuels** [comment]
It's worth reading how django-cms manages multilingual content - http://docs.django-cms.org/en/support-3.0.x/topics/multiple_languages.html
Also, how they handle Draft states: http://docs.django-cms.org/en/support-3.0.x/topics/publishing.html
